### ISSUE TITLE
关于测试代码

### ISSUE THREAD

**Issue by Litchi1999** [jessapinkman/TSTNN#1]
您好我想问下加上if __name__ == '__main__':后出现警告
RuntimeWarning: invalid value encountered in scalar divide
  rcoeff = (R[i + 1] - sum_term) / E
是怎么回事呢

**Comment by Litchi1999** [comment]
还有就是要怎么加上if __name__ == '__main__':这一句呢

**Comment by jessapinkman** [comment]
May be the problem of dataset, I wonder have you prepared the dataset correctly. you can get the dataset from [here](https://datashare.ed.ac.uk/handle/10283/1942). Hope that may help u!
