### ISSUE TITLE
关于新的实验

### ISSUE THREAD

**Issue by Litchi1999** [jessapinkman/TSTNN#2]
作者您好！请问可以分享一下加入小波变换后的代码吗

**Comment by jessapinkman** [comment]
I no longer do this work, and the previous code has not been backed up. However, you can add wavelet transform to the encoder section and complete the inverse transform at the end of the encoding. Hope this may help u.

**Comment by Litchi1999** [comment]
> 我不再做这项工作，并且以前的代码尚未备份。但是，您可以将小波变换添加到编码器部分，并在编码结束时完成逆变换。希望这对你有帮助。

Thanks，thats helpful

**Comment by Litchi1999** [comment]
> 我不再做这项工作，并且以前的代码尚未备份。但是，您可以将小波变换添加到编码器部分，并在编码结束时完成逆变换。希望这对你有帮助。

您好，我还是想问一下是应该直接添加在编码器部分的定义之前还是在数据加载和预处理阶段呢？

**Comment by jessapinkman** [comment]
Generally speaking, it is necessary to complete the transformation in the encoder section. You can refer to some other speech enhancement methods based on Fourier transform
